notifications:
  email: false
sudo: false
language: node_js
node_js:
- 6.9.1
- 10.14.0
before_script:
- npm install -g gulp
before_install:
- npm i
script:
- npm test
after_success:
- npm run-script coverage
before_deploy:
- npm run-script build
deploy:
  provider: npm
  skip_cleanup: true
  email: admin@inspirehep.net
  api_key:
    secure: yiO3fR9F5wnqBWs3G/XQcbaE/8l59WXnauQOvqaDIJp4rdo3KPGWEGHCRYRSWKLRXyF8f9YbYEVLrevk5/RDqExnXHAS2mMFRPp0+kgMoIW65mmIbWZ4OOBvczpvBZ7GFwPJGz887zl7nRwIc4pyOIOIEBiVdkFETf5uzou97oWj95pj44Y7ecBpiYkpMM5vF4kLWXm0CQEX5v21nuar4GiioyPkkaNpGyYzU5/XSUudQCyz2rrnZ/7a571B/MmEqN6d+3m6Anmzkde5Wni50by3Z1jUXEgLuRdFsXMGeLPp5WmW2RJhdurgY49qlCBXhjLyXnb3cDkIv/HJCZCT7krUSBAaWGNhmKY3QQVsnBQcQV6ox6jkYbP3pkEHhKh6epnMsyVCkE1FtKOBpf2qAiNDxPZDt6Kej6/KMWjeSTAuxcN3vxDjb4kppeDk8DtORRc+7bqJpuWifl3cR2iY9xiEPszBKfP0vmtCkSw/wQKeOr2v0o+If2BVA/MAkHpzYOsFiEas6ymvcsgewui2YOH1tLyqPyZvZ1DcP9QC2kUTVtXeb+pqnkFSyfNWkn+5gw6krhhEZJOFEiEGluuk/xsIuY6IPrPhKrYQlyf9mwLbZMXuCkFcnvxJdvZYZoXp4Dmf7IwmDGn11dmfDDfTsM3shU0nBCGGsfKyUxAuYrM=
  on:
    tags: true
    repo: inspirehep/inspirehep-search-js
    branch: master
    node: 6.9.1
