name: Test and release

on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.14.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm install

      - name: Test
        run: npm test

      - name: Build
        if: ${{ success() && github.event_name == 'release' }}
        run: npm build

      - name: Publish
        if: ${{ success() && github.event_name == 'release' }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
